/** Maps legacy Ionicons / Material names to Lucide-compatible keys in lucideIconMap. */
export const FLATICON_ALIASES: Record<string, string> = {
  // Navigation & UI
  add: 'plus',
  'add-circle': 'plus',
  'add-circle-outline': 'plus',
  'arrow-back': 'angle-left',
  'arrow-forward': 'angle-right',
  'chevron-back': 'angle-left',
  'chevron-down': 'angle-down',
  'chevron-forward': 'angle-right',
  'chevron-up': 'angle-up',
  close: 'cross',
  'close-circle': 'cross-circle',
  'close-circle-outline': 'cross-circle',
  menu: 'menu-burger',
  'ellipsis-horizontal': 'menu-dots',
  navigate: 'navigation',
  locate: 'target',
  refresh: 'refresh',
  'gesture-tap': 'hand',
  'repeat-outline': 'arrows-repeat',
  'refresh-circle-outline': 'refresh',

  // Auth & user
  person: 'user',
  'person-outline': 'user',
  'person-add-outline': 'user-add',
  'people-outline': 'users',
  'shield-account-outline': 'user-shield',
  'log-out-outline': 'sign-out-alt',

  // Communication
  'at-outline': 'at',
  chat: 'comment',
  'chatbubble-ellipses': 'comment-alt',
  'chatbubble-ellipses-outline': 'comment-alt',
  'chatbubble-outline': 'comment',
  chatbubbles: 'comments',
  'chatbubbles-outline': 'comments',
  'message-text-outline': 'comment-alt',
  mail: 'envelope',
  'mail-outline': 'envelope',
  'email-outline': 'envelope',
  'call-outline': 'phone-call',
  call: 'phone-call',
  send: 'paper-plane',
  'send-outline': 'paper-plane',
  'paper-plane-outline': 'paper-plane',
  whatsapp: 'comment',

  // Media
  camera: 'camera',
  'camera-outline': 'camera',
  'camera-reverse-outline': 'refresh',
  'image-outline': 'picture',
  'images-outline': 'images',
  videocam: 'video-camera',
  'videocam-off': 'video-slash',
  mic: 'microphone',
  'mic-off': 'microphone-slash',
  'volume-high': 'volume',
  'volume-mute': 'volume-mute',
  broadcast: 'signal-stream',
  radio: 'signal-stream',

  // Actions
  checkmark: 'check',
  'check-bold': 'check',
  'checkmark-circle': 'badge-check',
  'checkmark-circle-outline': 'badge-check',
  'check-circle': 'badge-check',
  'check-circle-outline': 'badge-check',
  'checkmark-done': 'check-double',
  'checkmark-done-outline': 'check-double',
  create: 'edit',
  'create-outline': 'edit',
  'pencil-outline': 'edit',
  'pencil-plus': 'pen-square',
  edit: 'edit',
  'cut-outline': 'scissors',
  'scissors-cutting': 'scissors',
  'trash-outline': 'trash',
  remove: 'minus-circle',
  'auto-fix': 'magic-wand',
  flag: 'flag',
  'flag-outline': 'flag',

  // Visibility
  eye: 'eye',
  'eye-outline': 'eye',
  'eye-off-outline': 'eye-crossed',

  // Commerce & listings
  'bag-add-outline': 'shopping-bag-add',
  'bag-outline': 'shopping-bag',
  'storefront-outline': 'shop',
  storefront: 'shop',
  'store-outline': 'shop',
  pricetag: 'tags',
  'pricetag-outline': 'tags',
  tag: 'tags',
  'tag-multiple': 'tags',
  'tag-plus': 'tags',
  'cart-outline': 'shopping-cart',

  // Content
  home: 'home',
  search: 'search',
  'search-outline': 'search',
  newspaper: 'newspaper',
  'document-text': 'document',
  'document-text-outline': 'document',
  'file-document-outline': 'document',
  'file-export-outline': 'file-export',
  'folder-open-outline': 'folder-open',
  'clipboard-outline': 'clipboard',
  'clipboard-list-outline': 'clipboard-list',
  'receipt-outline': 'receipt',
  'stats-chart-outline': 'chart-histogram',
  'bar-chart-outline': 'chart-histogram',
  'bar-chart': 'chart-histogram',
  dashboard: 'dashboard',
  'trending-up': 'chart-line-up',
  'trending-up-outline': 'chart-line-up',
  'view-grid-outline': 'apps',
  'view-list': 'list',

  // Social
  heart: 'heart',
  'heart-outline': 'heart',
  'share-outline': 'share',
  'share-social-outline': 'share',
  'bookmark-outline': 'bookmark',
  star: 'star',
  'star-outline': 'star',

  // Location & map
  location: 'marker',
  'location-outline': 'marker',
  'map-marker-outline': 'marker',
  'map-outline': 'map',
  map: 'map',
  earth: 'globe',
  'globe-outline': 'globe',

  // Security & trust
  'shield-checkmark': 'shield-check',
  'shield-checkmark-outline': 'shield-check',
  'shield-check': 'shield-check',
  'shield-check-outline': 'shield-check',
  'shield-outline': 'shield',
  'shield-lock': 'lock',
  'lock-closed': 'lock',
  'lock-closed-outline': 'lock',
  'lock-outline': 'lock',

  // Settings & info
  'cog-outline': 'settings',
  'settings-outline': 'settings',
  'information-outline': 'info',
  'information-circle-outline': 'info',
  'alert-circle-outline': 'exclamation',
  'warning-outline': 'triangle-warning',
  warning: 'triangle-warning',
  'bell-outline': 'bell',
  'notifications-outline': 'bell',

  // Subscription & payment
  'gift-outline': 'gift',
  'diamond-outline': 'diamond',
  'crown-outline': 'crown',
  crown: 'crown',
  'credit-card-outline': 'credit-card',
  'credit-card-check-outline': 'credit-card',
  'cash-multiple': 'coins',

  // Theme
  'weather-night': 'moon',
  'white-balance-sunny': 'sun',
  'theme-light-dark': 'brightness',

  // Live / tools
  'calendar-outline': 'calendar',
  'time-outline': 'clock',
  'clock-outline': 'clock',
  'link-outline': 'link',
  'cube-outline': 'cube',
  tools: 'tool-box',
  'truck-delivery-outline': 'box',
  'food-apple-outline': 'apple-whole',
  gavel: 'gavel',

  // Animals (butcher categories)
  cow: 'cow',
  sheep: 'sheep',
  horse: 'horse',
  'horse-variant': 'horse',
  bird: 'bird',
  paw: 'paw',

  pin: 'pin',
  'rocket-outline': 'rocket',
  play: 'play',
  'settings-sliders': 'settings-sliders',
  'sort-alt': 'sort-alt',
  'menu-dots-vertical': 'menu-dots-vertical',
  'card-outline': 'card-outline',
  'bicycle-outline': 'bicycle-outline',
  'help-circle-outline': 'help-circle-outline',
  'signal-stream': 'signal-stream',

  // Misc legacy
};

export function resolveFlaticonIcon(name: string): string {
  return FLATICON_ALIASES[name] ?? name;
}
