/**
 * Lucide stroke icons — unified 20–22px, strokeWidth 2.
 */
import type { LucideIcon } from 'lucide-react-native';
import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  AtSign,
  BadgeCheck,
  Ban,
  Bell,
  Bike,
  Bird,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  CircleUser,
  Clipboard,
  ClipboardList,
  Clock,
  CreditCard,
  Crown,
  Diamond,
  Edit,
  Eye,
  EyeOff,
  FileText,
  Flag,
  Flame,
  FolderOpen,
  Gift,
  Globe,
  Hand,
  Headphones,
  Heart,
  Home,
  Image,
  Images,
  Info,
  LayoutGrid,
  Leaf,
  LifeBuoy,
  Link,
  List,
  ListFilter,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  MicOff,
  Milk,
  MinusCircle,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Navigation,
  Newspaper,
  Paperclip,
  Pause,
  PawPrint,
  PenLine,
  Phone,
  PhoneCall,
  Pin,
  Play,
  Plus,
  Radio,
  Receipt,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Settings,
  Share2,
  CornerUpRight,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  Tags,
  Ticket,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  UserCog,
  UserPlus,
  Users,
  UtensilsCrossed,
  Video,
  VideoOff,
  Volume2,
  VolumeX,
  Wand2,
  Wrench,
  X,
  XCircle,
} from 'lucide-react-native';
import { FLATICON_ALIASES } from '@/lib/flaticonAliases';

export const DEFAULT_ICON_SIZE = 21;
export const ICON_STROKE = 2;

const MAP: Record<string, LucideIcon> = {
  plus: Plus,
  add: Plus,
  'add-circle-outline': Plus,
  'angle-left': ChevronLeft,
  'arrow-back': ArrowLeft,
  'chevron-back': ChevronLeft,
  'angle-right': ChevronRight,
  'arrow-forward': ArrowRight,
  'chevron-forward': ChevronRight,
  'angle-down': ChevronDown,
  'chevron-down': ChevronDown,
  'angle-up': ChevronUp,
  'chevron-up': ChevronUp,
  cross: X,
  close: X,
  'cross-circle': XCircle,
  'close-circle': XCircle,
  'close-circle-outline': XCircle,
  'menu-burger': Menu,
  menu: Menu,
  'menu-dots': MoreHorizontal,
  'ellipsis-horizontal': MoreHorizontal,
  'ellipsis-vertical': MoreVertical,
  'menu-dots-vertical': MoreVertical,
  'more-vertical': MoreVertical,
  navigation: Navigation,
  navigate: Navigation,
  target: MapPin,
  locate: MapPin,
  refresh: RefreshCw,
  'arrows-repeat': RefreshCw,
  'refresh-circle-outline': RefreshCw,
  'camera-reverse-outline': RefreshCw,
  hand: PenLine,
  'gesture-tap': PenLine,
  user: User,
  person: User,
  'person-outline': User,
  'user-add': UserPlus,
  'person-add-outline': UserPlus,
  users: Users,
  'people-outline': Users,
  'user-shield': Shield,
  'shield-account-outline': Shield,
  'sign-out-alt': LogOut,
  'log-out-outline': LogOut,
  at: AtSign,
  'at-outline': AtSign,
  comment: MessageSquare,
  'comment-alt': MessageCircle,
  'message-text-outline': MessageCircle,
  chat: MessageSquare,
  'chatbubble-outline': MessageSquare,
  'chatbubble-ellipses': MessageCircle,
  'chatbubble-ellipses-outline': MessageCircle,
  comments: MessagesSquare,
  chatbubbles: MessagesSquare,
  'chatbubbles-outline': MessagesSquare,
  envelope: Mail,
  mail: Mail,
  'mail-outline': Mail,
  'email-outline': Mail,
  'phone-call': PhoneCall,
  'call-outline': PhoneCall,
  call: Phone,
  'paper-plane': Send,
  'paper-plane-outline': Send,
  send: Send,
  'send-outline': Send,
  picture: Image,
  'image-outline': Image,
  images: Images,
  'images-outline': Images,
  'video-camera': Video,
  videocam: Video,
  'videocam-outline': Video,
  'video-slash': VideoOff,
  'videocam-off': VideoOff,
  microphone: Mic,
  mic: Mic,
  'microphone-slash': MicOff,
  'mic-off': MicOff,
  volume: Volume2,
  'volume-high': Volume2,
  'volume-mute': VolumeX,
  'signal-stream': Radio,
  broadcast: Radio,
  radio: Radio,
  check: Check,
  checkmark: Check,
  'check-bold': Check,
  'badge-check': BadgeCheck,
  'checkmark-circle': BadgeCheck,
  'checkmark-circle-outline': BadgeCheck,
  'check-circle': BadgeCheck,
  'check-circle-outline': BadgeCheck,
  'check-double': CheckCheck,
  'checkmark-done': CheckCheck,
  'checkmark-done-outline': CheckCheck,
  edit: Edit,
  create: Edit,
  'create-outline': Edit,
  'pencil-outline': Edit,
  'pencil-plus': PenLine,
  scissors: PenLine,
  'cut-outline': PenLine,
  'scissors-cutting': PenLine,
  trash: Trash2,
  'trash-outline': Trash2,
  'minus-circle': MinusCircle,
  remove: MinusCircle,
  'magic-wand': Wand2,
  'auto-fix': Wand2,
  flag: Flag,
  'flag-outline': Flag,
  eye: Eye,
  'eye-outline': Eye,
  'eye-crossed': EyeOff,
  'eye-off-outline': EyeOff,
  'shopping-bag-add': ShoppingBag,
  'bag-add-outline': ShoppingBag,
  'shopping-bag': ShoppingBag,
  'bag-outline': ShoppingBag,
  shop: Store,
  storefront: Store,
  'storefront-outline': Store,
  'store-outline': Store,
  tags: Tags,
  tag: Tag,
  pricetag: Tag,
  'pricetag-outline': Tag,
  'tag-multiple': Tags,
  'tag-plus': Tags,
  'shopping-cart': ShoppingCart,
  'cart-outline': ShoppingCart,
  home: Home,
  search: Search,
  'search-outline': Search,
  newspaper: Newspaper,
  'newspaper-outline': Newspaper,
  document: FileText,
  'document-text': FileText,
  'document-text-outline': FileText,
  'file-document-outline': FileText,
  'file-export': FileText,
  'file-export-outline': FileText,
  'folder-open': FolderOpen,
  'folder-open-outline': FolderOpen,
  clipboard: Clipboard,
  'clipboard-outline': Clipboard,
  'clipboard-list': ClipboardList,
  'clipboard-list-outline': ClipboardList,
  receipt: Receipt,
  'receipt-outline': Receipt,
  'chart-histogram': TrendingUp,
  'chart-line-up': TrendingUp,
  'stats-chart-outline': TrendingUp,
  'bar-chart-outline': TrendingUp,
  'bar-chart': TrendingUp,
  'trending-up': TrendingUp,
  'trending-up-outline': TrendingUp,
  apps: LayoutGrid,
  'view-grid-outline': LayoutGrid,
  dashboard: LayoutGrid,
  list: List,
  'view-list': List,
  heart: Heart,
  'heart-outline': Heart,
  share: Share2,
  'share-outline': Share2,
  'share-social-outline': Share2,
  'share-arrow': CornerUpRight,
  bookmark: Bookmark,
  'bookmark-outline': Bookmark,
  star: Star,
  'star-outline': Star,
  marker: MapPin,
  location: MapPin,
  'location-outline': MapPin,
  'map-marker-outline': MapPin,
  map: Map,
  'map-outline': Map,
  globe: Globe,
  earth: Globe,
  'globe-outline': Globe,
  'shield-check': ShieldCheck,
  'shield-checkmark': ShieldCheck,
  'shield-checkmark-outline': ShieldCheck,
  'shield-check-outline': ShieldCheck,
  shield: Shield,
  'shield-outline': Shield,
  'shield-lock': Shield,
  lock: Lock,
  'lock-closed': Lock,
  'lock-closed-outline': Lock,
  'lock-outline': Lock,
  settings: Settings,
  'cog-outline': Settings,
  'settings-outline': Settings,
  info: Info,
  'information-outline': Info,
  'information-circle-outline': Info,
  exclamation: AlertCircle,
  'alert-circle-outline': AlertCircle,
  'triangle-warning': TriangleAlert,
  warning: TriangleAlert,
  'warning-outline': TriangleAlert,
  bell: Bell,
  'bell-outline': Bell,
  'notifications-outline': Bell,
  gift: Gift,
  'gift-outline': Gift,
  diamond: Diamond,
  'diamond-outline': Diamond,
  crown: Crown,
  'crown-outline': Crown,
  copy: ClipboardList,
  'copy-outline': ClipboardList,
  'credit-card': CreditCard,
  'credit-card-outline': CreditCard,
  'credit-card-check-outline': CreditCard,
  'card-outline': CreditCard,
  coins: CreditCard,
  'cash-multiple': CreditCard,
  moon: Moon,
  'weather-night': Moon,
  sun: Sun,
  'sunny-outline': Sun,
  'white-balance-sunny': Sun,
  brightness: Sun,
  'theme-light-dark': Sun,
  calendar: Calendar,
  'calendar-outline': Calendar,
  clock: Clock,
  'time-outline': Clock,
  'clock-outline': Clock,
  link: Link,
  'link-outline': Link,
  cube: Box,
  'cube-outline': Box,
  'tool-box': Wand2,
  tools: Wand2,
  box: Box,
  'truck-delivery-outline': Box,
  'apple-whole': Tag,
  'food-apple-outline': Tag,
  gavel: Flag,
  pin: Pin,
  play: Play,
  pause: Pause,
  rocket: Rocket,
  'rocket-outline': Rocket,
  'settings-sliders': SlidersHorizontal,
  'sort-alt': ArrowUpDown,
  'bicycle-outline': Bike,
  whatsapp: MessageCircle,
  'help-circle': CircleHelp,
  'help-circle-outline': CircleHelp,
  verified: BadgeCheck,
  'check-decagram-outline': BadgeCheck,
  paperclip: Paperclip,
  camera: Camera,
  'camera-outline': Camera,
  megaphone: Megaphone,
  'megaphone-outline': Megaphone,
  'grid-outline': LayoutGrid,
  'briefcase-outline': Briefcase,
  'home-outline': Home,
  block: Ban,
  'hand-left-outline': Hand,
  'person-circle-outline': CircleUser,
  headset: Headphones,
  ticket: Ticket,
  'ticket-outline': Ticket,
  lifebuoy: LifeBuoy,
  'account-cog-outline': UserCog,
  flame: Flame,
  'navigate-outline': Navigation,
  'sparkles-outline': Sparkles,
  'options-outline': ListFilter,
  'trending-down': TrendingDown,
  bird: Bird,
  cow: Milk,
  sheep: PawPrint,
  horse: PawPrint,
  'horse-variant': PawPrint,
  paw: PawPrint,
  leaf: Leaf,
  truck: Truck,
  restaurant: UtensilsCrossed,
  construct: Wrench,
};

export function resolveLucideIcon(name: string): LucideIcon {
  if (MAP[name]) return MAP[name];
  const aliased = FLATICON_ALIASES[name];
  if (aliased && MAP[aliased]) return MAP[aliased];
  return Info;
}
