import { luxuryDark } from '@/constants/homeLuxury';
import { sarh } from '@/constants/sarhTokens';
import { colors } from './tokens/colors';
import { radius } from './tokens/radius';
import { spaceAlias } from './tokens/spacing';

/**
 * Compatibility map: live token path → foundation token.
 * Read-only documentation for phase 2. Screens keep using the old imports.
 */
export const LEGACY_TOKEN_MAP = {
  'sarh.color.bg': colors.background,
  'sarh.color.surface': colors.surface,
  'sarh.color.surfaceRaised': colors.surfaceElevated,
  'sarh.color.surfaceAlt': colors.surfaceAlt,
  'sarh.color.action': colors.primary,
  'sarh.color.actionPressed': colors.primaryPressed,
  'sarh.color.text': colors.textPrimary,
  'sarh.color.textSecondary': colors.textSecondary,
  'sarh.color.textMuted': colors.textMuted,
  'sarh.color.border': colors.border,
  'sarh.color.danger': colors.danger,
  'sarh.color.warning': colors.warning,
  'sarh.color.success': colors.success,
  'luxuryDark.bg': luxuryDark.bg,
  'luxuryDark.card': luxuryDark.card,
  'ds.dark.page': sarh.color.bg,
  'ds.dark.card': sarh.color.surface,
  'ds.dark.elevated': sarh.color.surfaceRaised,
  'ds.dark.primary': sarh.color.action,
  'sarh.space.xs': spaceAlias.xs,
  'sarh.space.sm': spaceAlias.sm,
  'sarh.space.md': spaceAlias.md,
  'sarh.space.lg': spaceAlias.lg,
  'sarh.space.xl': spaceAlias.xl,
  'sarh.space.xxl': spaceAlias.xxl,
  'sarh.space.xxxl': spaceAlias.xxxl,
  'sarh.radius.sm': radius[8],
  'sarh.radius.md': radius[12],
  'sarh.radius.lg': radius[16],
  'sarh.radius.xl': radius[20],
  'sarh.radius.pill': radius[999],
} as const;

/**
 * Hardcoded-value audit under `app/` (source files, excluding `__tests__` and `e2e`).
 * Counts are a snapshot for the foundation report — do not treat as a rewrite list.
 *
 * Generated by scanning `*.ts` / `*.tsx` for hex, rgba(), fontSize, fontWeight,
 * borderRadius, margin/padding/gap, and duration-like literals.
 */
export const HARDCODED_AUDIT = {
  scannedAt: '2026-09-06',
  /** Source files under `app/` excluding `__tests__`, `e2e`, and this foundation. */
  hex: 558,
  rgba: 209,
  fontSize: 75,
  fontWeight: 117,
  borderRadius: 649,
  spacingProps: 2386,
  animationDuration: 37,
  highGravityFiles: [
    'constants/theme.ts',
    'app/payment.tsx',
    'constants/sarhTokens.ts',
    'components/feature/StoryViewer.tsx',
    'app/live/create.tsx',
    'app/create/story.tsx',
    'app/live/watch/[id].tsx',
    'constants/designSystem.ts',
    'components/feature/ListingCard.tsx',
    'app/butchers/[id].tsx',
  ],
} as const;

export const PHASE_2_SCOPE = [
  'Core primitives live in `@/design-system/components` — adopt screen-by-screen',
  'Legacy `@/components/ui/AppText` + `theme.typography` resolve weight-aware Tajawal',
  'Replace hardcoded hex in payment / live / story / listing surfaces',
  'theme.ts danger/warning now alias sarh.color; rose/amber remain decorative',
  'Leave gold / rose / amber / liveRed as local accents — do not promote to brand tokens',
] as const;

/**
 * Font migration status — Tajawal is the sole app typeface for all text.
 */
export const FONT_WEIGHT_MIGRATION = [
  'components/ui/AppText.tsx — weight-aware Tajawal (no Bold force)',
  'constants/theme.ts typography — roles map to Tajawal 500/600/700 faces',
  'PostItem — Tajawal via resolveAppFontFace (same as the rest of the app)',
] as const;
