-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "about" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicPhone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicEmail" TEXT;

-- AlterTable
ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "feeText" TEXT;
ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "isFree" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "steps" TEXT;
ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "conditions" TEXT;
ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "documents" TEXT;
ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "deliveryChannel" TEXT;
ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS "services_sortOrder_idx" ON "services"("sortOrder");
