-- AddListingVideoFields
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "videoUrl" TEXT;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "thumbnailUrl" TEXT;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "videoDuration" DOUBLE PRECISION;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "videoWidth" INTEGER;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "videoHeight" INTEGER;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "videoFileSize" INTEGER;
